/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    news: News;
    tools: Tool;
    'team-members': TeamMember;
    partners: Partner;
    media: Media;
    modules: Module;
    'service-plans': ServicePlan;
    entitlements: Entitlement;
    orders: Order;
    organizations: Organization;
    'payment-events': PaymentEvent;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    'service-plans': ServicePlansSelect<false> | ServicePlansSelect<true>;
    entitlements: EntitlementsSelect<false> | EntitlementsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'payment-events': PaymentEventsSelect<false> | PaymentEventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en') | ('uk' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'uk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-идентификатор. Заполняется автоматически из заголовка, можно изменить.
   */
  slug: string;
  /**
   * general → /slug; legal → /legal/slug (оферта, политика).
   */
  section: 'general' | 'legal';
  /**
   * Соберите страницу из блоков (ТЗ §8.3).
   */
  layout: (
    | HeroBlock
    | StatsBlock
    | FeatureGridBlock
    | ToolsBlock
    | PricingBlock
    | RichTextBlock
    | TeamBlock
    | PartnersBlock
    | CTABlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  subheading?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  intro?: string | null;
  features?:
    | {
        title: string;
        description?: string | null;
        icon?: ('map' | 'calc' | 'report' | 'api' | 'bot' | 'spark') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolsBlock".
 */
export interface ToolsBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Если пусто — покажем все активные инструменты по порядку.
   */
  tools?: (number | Tool)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'toolsShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  title: string;
  /**
   * URL-идентификатор. Заполняется автоматически из заголовка, можно изменить.
   */
  slug: string;
  /**
   * Короткое описание для карточки.
   */
  summary: string;
  icon?: ('map' | 'calc' | 'report' | 'api' | 'bot' | 'spark') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Порядок сортировки.
   */
  order?: number | null;
  isActive?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Платный/защищённый файл (выдача по токену) — логика этапа 5.
   */
  accessControlled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Сноска под тарифами (напр. про безнал для юрлиц).
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('normal' | 'narrow') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock".
 */
export interface TeamBlock {
  heading?: string | null;
  intro?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'team';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading: string;
  text?: string | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL-идентификатор. Заполняется автоматически из заголовка, можно изменить.
   */
  slug: string;
  publishedAt?: string | null;
  /**
   * Краткий анонс для ленты и SEO-описания.
   */
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  url?: string | null;
  logo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  name: string;
  /**
   * Технический ключ модуля (неизменяемый идентификатор).
   */
  key:
    | 'geoportal'
    | 'arm-analytics'
    | 'express-valuation'
    | 'report-generator'
    | 'interactive-report'
    | 'appraiser-calculator'
    | 'portfolio-valuation'
    | 'auto-valuation';
  /**
   * URL-идентификатор. Заполняется автоматически из заголовка, можно изменить.
   */
  slug: string;
  summary?: string | null;
  icon?: ('map' | 'calc' | 'report' | 'api' | 'bot' | 'spark') | null;
  accessType: 'quota' | 'period' | 'free';
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans".
 */
export interface ServicePlan {
  id: number;
  name: string;
  /**
   * Модуль, к которому даёт доступ пакет.
   */
  module: number | Module;
  /**
   * Доп. модули бандла (напр. калькулятор + АРМ Аналітика).
   */
  grantsModules?: (number | Module)[] | null;
  accessType: 'quota' | 'period';
  packLevel?: ('min' | 'mid' | 'max') | null;
  /**
   * Число запросов в пакете.
   */
  quota?: number | null;
  /**
   * Длительность доступа, дней.
   */
  periodDays?: number | null;
  /**
   * Цена в копейках (источник истины).
   */
  priceMinor: number;
  /**
   * Цена для отображения (грн).
   */
  price: number;
  currency: 'UAH' | 'USD' | 'EUR';
  /**
   * Короткий подзаголовок пакета.
   */
  tagline?: string | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  billingPeriod?: ('month' | 'year' | 'one-time') | null;
  /**
   * Число мест (для корп.).
   */
  seats?: number | null;
  /**
   * Выделить как популярный.
   */
  highlighted?: boolean | null;
  order?: number | null;
  isActive?: boolean | null;
  /**
   * Надпись на кнопке (по умолчанию «Купить»).
   */
  ctaLabel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements".
 */
export interface Entitlement {
  id: number;
  user?: (number | null) | User;
  /**
   * Заполняется для корпоративных доступов.
   */
  organization?: (number | null) | Organization;
  module: number | Module;
  accessType: 'quota' | 'period';
  quotaTotal?: number | null;
  /**
   * БД — источник истины; Redis кэширует горячий счётчик.
   */
  quotaRemaining?: number | null;
  /**
   * Для period-доступа.
   */
  periodEnd?: string | null;
  status: 'active' | 'exhausted' | 'expired' | 'canceled' | 'past_due';
  /**
   * Доступ держится до конца периода, далее — canceled.
   */
  cancelAtPeriodEnd?: boolean | null;
  autoRenew?: boolean | null;
  /**
   * Токен карты провайдера (для рекуррента).
   */
  cardToken?: string | null;
  /**
   * Сумма продления, копейки.
   */
  renewPriceMinor?: number | null;
  /**
   * Длительность продления, дней.
   */
  renewPeriodDays?: number | null;
  /**
   * Грейс при past_due — доступ до этой даты.
   */
  pastDueUntil?: string | null;
  /**
   * Заказы, продлившие этот доступ.
   */
  sourceOrders?: (number | Order)[] | null;
  lastConsumedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'editor' | 'customer' | 'api')[] | null;
  /**
   * Корпоративный аккаунт (для мест/безнала).
   */
  organization?: (number | null) | Organization;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * ЄДРПОУ
   */
  edrpou?: string | null;
  /**
   * ІПН
   */
  ipn?: string | null;
  billingEmail?: string | null;
  owner?: (number | null) | User;
  members?: (number | User)[] | null;
  /**
   * Лимит мест (из тарифа); логика seats — этап 6.
   */
  seatsLimit?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  user?: (number | null) | User;
  /**
   * Если задано — доступ выдаётся организации (корп-покупка).
   */
  organization?: (number | null) | Organization;
  status: 'new' | 'awaiting_invoice' | 'pending' | 'paid' | 'failed' | 'fulfilled' | 'canceled';
  customerName?: string | null;
  email?: string | null;
  phone?: string | null;
  billingAddress?: string | null;
  /**
   * Реквизиты юрлица для безнала (счёт/акт). Наличие ⇒ B2B.
   */
  legalEntity?: {
    name?: string | null;
    /**
     * ЄДРПОУ
     */
    edrpou?: string | null;
    /**
     * ІПН
     */
    ipn?: string | null;
    iban?: string | null;
    bankName?: string | null;
  };
  items?:
    | {
        refType: 'plan' | 'research' | 'library';
        plan?: (number | null) | ServicePlan;
        qty?: number | null;
        /**
         * Цена позиции в копейках на момент заказа.
         */
        priceMinorSnapshot: number;
        titleSnapshot?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Итого в копейках.
   */
  totalMinor: number;
  currency: 'UAH' | 'USD' | 'EUR';
  paymentMethod: 'card' | 'invoice';
  provider?: ('mock' | 'monobank' | 'liqpay') | null;
  /**
   * invoiceId провайдера.
   */
  paymentRef?: string | null;
  /**
   * Рахунок-фактура (PDF).
   */
  invoiceFile?: (number | null) | Media;
  /**
   * Акт (PDF).
   */
  actFile?: (number | null) | Media;
  paidAt?: string | null;
  fulfilledAt?: string | null;
  /**
   * Токены защищённой выдачи файлов (разовые продажи) — резерв.
   */
  downloadTokens?:
    | {
        token?: string | null;
        expiresAt?: string | null;
        maxDownloads?: number | null;
        downloadCount?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events".
 */
export interface PaymentEvent {
  id: number;
  /**
   * `{invoiceId}:{status}` — ключ идемпотентности.
   */
  eventId: string;
  provider: 'mock' | 'monobank' | 'liqpay';
  invoiceId?: string | null;
  order?: (number | null) | Order;
  type?: string | null;
  status?: string | null;
  signatureValid?: boolean | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  result?: ('applied' | 'duplicate' | 'ignored' | 'error') | null;
  error?: string | null;
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'service-plans';
        value: number | ServicePlan;
      } | null)
    | ({
        relationTo: 'entitlements';
        value: number | Entitlement;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'payment-events';
        value: number | PaymentEvent;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  section?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        toolsShowcase?: T | ToolsBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        team?: T | TeamBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  ctaLabel?: T;
  ctaHref?: T;
  secondaryLabel?: T;
  secondaryHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ToolsBlock_select".
 */
export interface ToolsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  tools?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamBlock_select".
 */
export interface TeamBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  content?: T;
  order?: T;
  isActive?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  accessControlled?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  accessType?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans_select".
 */
export interface ServicePlansSelect<T extends boolean = true> {
  name?: T;
  module?: T;
  grantsModules?: T;
  accessType?: T;
  packLevel?: T;
  quota?: T;
  periodDays?: T;
  priceMinor?: T;
  price?: T;
  currency?: T;
  tagline?: T;
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  billingPeriod?: T;
  seats?: T;
  highlighted?: T;
  order?: T;
  isActive?: T;
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entitlements_select".
 */
export interface EntitlementsSelect<T extends boolean = true> {
  user?: T;
  organization?: T;
  module?: T;
  accessType?: T;
  quotaTotal?: T;
  quotaRemaining?: T;
  periodEnd?: T;
  status?: T;
  cancelAtPeriodEnd?: T;
  autoRenew?: T;
  cardToken?: T;
  renewPriceMinor?: T;
  renewPeriodDays?: T;
  pastDueUntil?: T;
  sourceOrders?: T;
  lastConsumedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  organization?: T;
  status?: T;
  customerName?: T;
  email?: T;
  phone?: T;
  billingAddress?: T;
  legalEntity?:
    | T
    | {
        name?: T;
        edrpou?: T;
        ipn?: T;
        iban?: T;
        bankName?: T;
      };
  items?:
    | T
    | {
        refType?: T;
        plan?: T;
        qty?: T;
        priceMinorSnapshot?: T;
        titleSnapshot?: T;
        id?: T;
      };
  totalMinor?: T;
  currency?: T;
  paymentMethod?: T;
  provider?: T;
  paymentRef?: T;
  invoiceFile?: T;
  actFile?: T;
  paidAt?: T;
  fulfilledAt?: T;
  downloadTokens?:
    | T
    | {
        token?: T;
        expiresAt?: T;
        maxDownloads?: T;
        downloadCount?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  edrpou?: T;
  ipn?: T;
  billingEmail?: T;
  owner?: T;
  members?: T;
  seatsLimit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events_select".
 */
export interface PaymentEventsSelect<T extends boolean = true> {
  eventId?: T;
  provider?: T;
  invoiceId?: T;
  order?: T;
  type?: T;
  status?: T;
  signatureValid?: T;
  rawPayload?: T;
  result?: T;
  error?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  organization?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  headerNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * Ссылка на Telegram-бот/канал.
   */
  telegram?: string | null;
  footerCtaText?: string | null;
  footerCtaLabel?: string | null;
  footerCtaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  headerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  email?: T;
  phone?: T;
  address?: T;
  telegram?: T;
  footerCtaText?: T;
  footerCtaLabel?: T;
  footerCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}